### ISSUE TITLE
A4 - Feedback

### ISSUE THREAD

**Issue by Plagiatus** [Swampowl/GIS-SoSe-2020#1]
Ampelgründe
- Dutzende Errors auf jeder Seite.
- nur ein Media Query. und dann auch noch an einer anderen wie der vorgeschriebenen Breite.
- width:25% wird gerade bei kleineren Breiten absolut unbenutzbar.
- Seite nicht responsiv wie gefordert.

Weiteres
- das für Mobil geänderte Menu ist super (auch wenn im Impressum die Frontpage falsch verlinkt ist)

**Comment by Swampowl** [comment]
Queries geadded, Errors gefixt. Seite sollte jetzt responsiv sein.
Allerdings unter 250px Breite nicht geschafft.

**Comment by Plagiatus** [comment]
unter 250 ist auch echt wenig Platz zum arbeiten, das ist schon okay.

**Comment by Swampowl** [comment]
Gucci. Magst dann noch die Ampel ändern? :P

**Comment by Plagiatus** [comment]
mach ich gerne nach deiner erfolgreichen Verteidigung im Praktikum.
